name: 'Extra environment variables'
description: 'Export extra environment variables for the following steps'
author: 'Vlad Dmitrievich'
inputs:
  token:
    required: true
    description: 'Authentication token'
    default: ${{ github.token }}
  prefix:
    required: true
    description: 'Prefix for environment variables'
    default: 'EXTRA'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'dollar-sign'
  color: 'gray-dark'
