name: 'Extra environment variables'
description: 'Export extra environment variables for the following jobs'
author: 'Vlad Dmitrievich'
inputs:
  token:
    required: false
    description: 'Authentication token'
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
